### ISSUE TITLE
Suggest delete of match

### ISSUE THREAD

**Issue by jCobbSK** [jCobbSK/sport-ranking#8]
If both players sign same match for deletion, it will be deleted and points will be return.

**Comment by boobiq** [comment]
but match is deleted, all later matches should be recalculated, because points would be different if that match didn't exist :)

**Comment by jCobbSK** [comment]
That is true, but this option should be used mostly if user put wrong score or messed up creating match form otherwise.

**Comment by boobiq** [comment]
okay, so then maybe allow deleting only when it's the last match for both players
